skills = [
    "python",
    "sql",
    "excel",
    "power bi",
    "tableau",
    "machine learning",
    "deep learning",
    "react",
    "next.js",
    "fastapi",
    "aws",
    "azure",
    "docker",
    "git",
    "github",
    "javascript",
    "typescript",
    "node.js",
    "mongodb",
    "mysql",
    "postgresql",
    "data analytics",
    "powerpoint",
    "pandas",
    "numpy",
    "tensorflow",
    "scikit-learn",
    "java",
    "c++",
    "html",
    "css"
]